# Generated by Django 5.2.17 on 2026-09-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Professional headshot — displays in the hero section",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
