# Generated by Django 5.2.17 on 2026-09-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_siteconfig_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(blank=True, max_length=200)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("tutorial", "Tutorial / Video Course"),
                            ("article", "Article"),
                            ("course", "Online Course"),
                            ("video", "YouTube / Video"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="resources/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "date_consumed",
                    models.DateField(
                        blank=True, help_text="When you read/watched it", null=True
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1–5 stars", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-date_consumed", "resource_type"],
            },
        ),
    ]
